### ISSUE TITLE
Can Import namespace in Controller File ?

### ISSUE THREAD

**Issue by GAMITG** [mdmsoft/import#1]
Hello,

I have used this extension for import the namespace, and its works fine. when i import all namespace in view file or  `web.php`  file so its works good but in controller file all namespace not imported.

so, can you give me idea for import namespaces in controller file.

Thanks in Advance

**Comment by mdmunir** [comment]
You can do wherever you want

``` php
namespace app\controllers;

use ...;

Import::using('yii\helpers\Html');

class MyController extends Controller
{
    ...
}
```

**Comment by GAMITG** [comment]
But my situation is that,
I have use `Import::using('yii\helpers\*');` in web.php so, its imported in view files but not imported in controller file.
so what i do ?

**Comment by mdmunir** [comment]
i see... try to add prefix `\`.

``` php
return \Json::encode($something);
```

**Comment by GAMITG** [comment]
I have put prefix `\` but nothing solve.
I have attached my some code.

in web.php

``` <?php

$params = require(__DIR__ . '/params.php');

Import::using('yii\widgets\*'); // import all class under namespace yii\widgets
// or  Import::using('\yii\widgets\*'); 
$config = [
   // 'layout' => 'column2',
    'id' => 'EduSec Combine',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
]
?>
```

**Comment by mdmunir** [comment]
i mean. not when define `Import::using()` but when call class. Use `\Html::xxx` instead of `Html::xxx`

**Comment by GAMITG** [comment]
I have solved it. and now working fine.
Thanks ... :blush:
